full_rebuild: true
name: A network of collaboration between Caribbean marine research institutions
author: Ramirez-Ramirez et al. (2016)
version:
encoding: utf-8
defaults:
  -
    values:
      layout: "index"
markdown: kramdown
kramdown:
  input: GFM
relative_permalinks: false
collections:
- entries
sass:
  sass_dir: _sass
  style: :compressed
exclude: [
.git,
.gitignore,
README.md,
.sass-cache
]
