# Site settings
title: A collaboration network of institutions of marine science in the Caribbean
email: luismmontilla@gmail.com
url: https://luismmontilla.github.io/
description: Ramírez-Ramírez RD, Montilla LM, Cavada-Blanco F and Croquer A. Identification of strengths and weaknesses of cooperative efforts within the wider Caribbean using a collaboration network approach [version 1; not peer reviewed]. F1000Research 2016, 5:799 (poster) (doi: 10.7490/f1000research.1111809.1)
# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Luis Miguel Montilla

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title:
    url:
  - title:
    url:
  - title:
    url:
  - title:
    url:
  - title:
    url:
  - title:
    url:
  - title:
    url:
  - title:
    url:

# Build settings
markdown: kramdown
permalink: pretty
